version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: gradle build
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            java -jar junit-platform-console-standalone.jar --class-path src/main/tests --scan-class-path
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
