version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: gradle build
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Download JUnit jar file
          command: |
              curl -o junit-platform-console-standalone-1.9.2.jar -L https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.2/junit-platform-console-standalone-1.9.2.jar
      - run:
          name: Run tests
          command: |
            java -jar junit-platform-console-standalone-1.9.2.jar --class-path . --scan-class-path
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
