version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: gradle build
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: gradle test
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
